[colors]
primary = "#B36B2F"
primary_container = "#E1A873"
primary_fixed_dim = "#9C5F2A"
on_primary = "#0E0703"
on_primary_container = "#120A06"
secondary = "#8E3A59"
secondary_container = "#C76A8E"
secondary_fixed_dim = "#7A314B"
on_secondary = "#12080C"
tertiary = "#315C7A"
tertiary_container = "#5D92B6"
on_tertiary = "#070B0E"
on_tertiary_container = "#0B1216"
surface = "#1A130F"
surface_dim = "#12100E"
surface_bright = "#2B2320"
surface_variant = "#3B2E27"
inverse_surface = "#E9E1D9"
on_surface = "#E9E1D9"
on_surface_variant = "#D6C8BE"
background = "#16110E"
on_background = "#E9E1D9"
outline = "#5E4C43"
outline_variant = "#463830"
shadow = "#000000"
scrim = "#000000"
inverse_primary = "#5E3A12"
inverse_on_surface = "#1C1712"
error = "#FF6B5E"
error_container = "#FFD7D2"